In [ ]:
%matplotlib inline


What is PyTorch?
===============

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

**Tensors**


Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [1]:
from __future__ import print_function
import torch
import numpy as np

Construct a 5x3 matrix, uninitialized:



In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[9.6429e-39, 9.2755e-39, 1.0286e-38],
        [9.0919e-39, 8.9082e-39, 9.2755e-39],
        [8.4490e-39, 1.0194e-38, 9.0919e-39],
        [8.4490e-39, 1.0653e-38, 9.9184e-39],
        [8.4490e-39, 8.9082e-39, 8.9082e-39]])


Construct a randomly initialized matrix:



In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7798, 0.7610, 0.7052],
        [0.5255, 0.0334, 0.7570],
        [0.6160, 0.2458, 0.4492],
        [0.0205, 0.5568, 0.4842],
        [0.3694, 0.0170, 0.1949]])


Construct a matrix filled zeros and of dtype long:



In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor basing on existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.7586,  0.8746, -0.9991],
        [ 1.8936,  0.2348, -0.0677],
        [ 1.1577,  1.7505, -1.5448],
        [ 1.1336, -0.9314,  0.1006],
        [-0.4938, -0.8942,  0.8226]])


Get its size:



In [7]:
print(x.shape)

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

**Operations**

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.7348,  1.7032, -0.0281],
        [ 2.1152,  0.3373,  0.2330],
        [ 1.9168,  2.6201, -0.8289],
        [ 2.0063, -0.8292,  0.9876],
        [ 0.3714, -0.1374,  1.4587]])


Addition: syntax 2



In [9]:
print(torch.add(x, y))

tensor([[-0.7348,  1.7032, -0.0281],
        [ 2.1152,  0.3373,  0.2330],
        [ 1.9168,  2.6201, -0.8289],
        [ 2.0063, -0.8292,  0.9876],
        [ 0.3714, -0.1374,  1.4587]])


Addition: providing an output tensor as argument



In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.7348,  1.7032, -0.0281],
        [ 2.1152,  0.3373,  0.2330],
        [ 1.9168,  2.6201, -0.8289],
        [ 2.0063, -0.8292,  0.9876],
        [ 0.3714, -0.1374,  1.4587]])


Addition: in-place



In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.7348,  1.7032, -0.0281],
        [ 2.1152,  0.3373,  0.2330],
        [ 1.9168,  2.6201, -0.8289],
        [ 2.0063, -0.8292,  0.9876],
        [ 0.3714, -0.1374,  1.4587]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [12]:
print(x[:3, 1])

tensor([0.8746, 0.2348, 1.7505])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``: (same behavior as numpy reshape)



In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [14]:
x = torch.randn(5)
print(x)
print(x.numpy())

tensor([ 1.7669, -0.8691,  1.2718,  1.2017,  0.5407])
[ 1.7668543  -0.8690975   1.2718102   1.2016764   0.54069835]


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

**Converting a Torch Tensor to a NumPy Array**


In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(type(b))

<class 'numpy.ndarray'>


See how the numpy array changed in value.



In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


**Converting NumPy Array to Torch Tensor**

See how changing the np array changed the Torch Tensor automatically



In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda:0")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    
    print(z)
    print(z.to("cpu", torch.double))  # ``.to`` can also change dtype together!
    print(z)

tensor([2.7669, 0.1309, 2.2718, 2.2017, 1.5407], device='cuda:0')
tensor([2.7669, 0.1309, 2.2718, 2.2017, 1.5407], dtype=torch.float64)
tensor([2.7669, 0.1309, 2.2718, 2.2017, 1.5407], device='cuda:0')


Or equivalently,

In [ ]:
x.cuda()

Note that before you can convert a tensor to numpy array, you first have to move it to RAM, otherwise it will give you an error:

In [20]:
x.numpy()

TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [21]:
print(x.cpu().numpy())

[ 1.7668543  -0.8690975   1.2718102   1.2016764   0.54069835]


One thing to note, however, is after some computations that has require_grad=True, if you want to convert the resulting tensor to numpy array, you will get an error:

In [22]:
x.requires_grad=True
y=torch.randn(1).cuda()
z=x+y
x.cpu().numpy()

RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

You first need to detach it from the autograd computation graph, then move it to RAM:

In [ ]:
print(x.detach().cpu().numpy())